name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t myuser/my-service:latest .
          docker push myuser/my-service:latest

      - name: Update ArgoCD values
        run: |
          git config --global user.email "ci@example.com"
          git config --global user.name "ci"
          git clone https://x-access-token:${{ secrets.REPO_TOKEN }}@github.com/tuusuario/argocd-config.git
          cd argocd-config/apps/my-service
          sed -i "s/tag:.*/tag: latest/" values.yaml
          git commit -am "Update tag"
          git push
